server:  
  image:
    repository: test

imagePullSecrets:
- name: <+secret.getvalue>

nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: false
  
pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false
  
alertmanager:
## If false, alertmanager will not be installed
##
  enabled: false
  useClusterRole: false

server:
  enabled: false
  useClusterRole: false
  namespaces:
    - cassie-dev