apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    chart: prometheus-14.3.0
    component: alertmanager
    heritage: Helm
    release: my-prometheus
  name: my-prometheus-alertmanager
  namespace: cassie-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: alertmanager
      release: my-prometheus
  template:
    metadata:
      labels:
        app: prometheus
        chart: prometheus-14.3.0
        component: alertmanager
        heritage: Helm
        release: my-prometheus
    spec:
      containers:
      - image: quay.io/prometheus/alertmanager:v0.21.0
        name: prometheus-alertmanager
      imagePullSecrets:
      - name: <+secrets.getValue("artifactoryluke")>