apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    version: 1.0
  name: copy-me
  namespace: cassie-prod
data:
  application.conf: |
    include "production"
    include "platform"
  logback.xml: |
    <configuration>
        <include resource="default-logback.xml"/>

        <root level="INFO">
            <appender-ref ref="STDOUT_JSON"/>
        </root>
    </configuration>
  platform.conf: |
    hopper: {
      app: {
        platform: {
          zookeeper: "zookeeper.zookeeper.svc.cluster.local:2181"
          singleton {
            connect: ${hopper.app.platform.zookeeper}
            path: "/hopper/singletons"
          }
        }
      }

      # for backwards compatibility
      platform: {
        services: {
          singleton: ${hopper.app.platform.zookeeper}
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    chart: prometheus-14.3.0
    component: alertmanager
    heritage: Helm
    release: my-prometheus
  name: my-prometheus-alertmanager
  namespace: cassie-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        image: quay.io/prometheus/alertmanager:v0.21.0
        imagePullPolicy: IfNotPresent
        name: prometheus-alertmanager
      imagePullSecrets:
      - name: <+secret.getvalue>